### ISSUE TITLE
Not work after update to 19.04

### ISSUE THREAD

**Issue by hectormartin42** [dpoetzsch/keyman#4]
After update my system to ubuntu 19.04, extension do not work and in system logs I found this Extension "keyman@dpoetzsch.github.com" had error: TypeError: this._construct is not a function

**Comment by dpoetzsch** [comment]
This is because gnome shell dropped support for `Lang.Class` in 3.32 (see https://gitlab.gnome.org/GNOME/gjs/issues/233). I will release a fix.
